    name: 'Hello World'
    description: 'Greet someone and record'
    inputs:
        who-to-greet: # id of input
        required: true
        default: 'World'
    outputs:
        time: # id of output
        description: 'The time we greeted you'
    runs:
        using: 'node12'
        main: 'index.js'