name: 'Hello World'
description: 'Greet someone and record'
runs-on: ubuntu-latest
  inputs:
    who-to-greet:
      default: 'World'
  outputs:
    time:
      description: 'The time we greeted you'
  runs:
    using: 'node12'
    main: 'index.js'