on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: crw-b/github-actions-practice@v1
        with:
          who-to-greet: 'Christina'
    # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"